{{- if (index .Values "graphql-gateway").enabled }}
{{- include "vaultdms.goServiceHPA" (dict "svcName" "graphql-gateway" "svc" (index .Values "graphql-gateway") "Values" .Values "Release" .Release "Chart" .Chart) }}
{{- end }}
