#!/usr/bin/env bash
# Bootstrap the COMPLETE SeDoc product on a fresh Ubuntu EC2 instance,
# using prebuilt images from ghcr.io/aieera/sedoc. Brings up the full stack
# (data plane + search/vectors + workflow + AV + all services/workers +
# gateway), builds & serves the web UI, and fronts it with Caddy.
#
# This is the "whole product" companion to deploy/ec2/bootstrap.sh (which
# only stands up the minimal API core). It runs the DEV / test posture
# (SEDOC_ALLOW_BYPASS_RLS=1, container Postgres/OpenSearch/MinIO) — good
# for a demo / pilot / UAT, NOT production. For production use the Helm chart
# (deploy/helm/sedoc) + managed RDS/OpenSearch/S3. See
# docs/deploy/ec2-full-stack.md §11.
#
# Usage (from the repo root, on the VM):
#   sudo PUBLIC_HOST=dms.yourdomain.com bash deploy/ec2/bootstrap-full.sh
#   # or, IP-only (HTTP, no TLS):
#   sudo bash deploy/ec2/bootstrap-full.sh
#
# Env knobs:
#   PUBLIC_HOST          domain (→ auto-HTTPS) or IP (→ HTTP). Default: EC2 public IPv4.
#   SEDOC_IMAGE_TAG   image tag to pull. Default: main.
#   ENABLE_ONLYOFFICE=1  also start OnlyOffice (in-browser DOCX/XLSX editing). Default: off.
#   SKIP_WEB=1           don't build/serve the web UI (API only). Default: build it.
#   SKIP_CADDY=1         don't install/configure Caddy. Default: configure it.
#   GO_VERSION           Go toolchain for the one-shot seed. Default: 1.23.4.
#
# Safe to re-run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"
IMAGE_TAG="${SEDOC_IMAGE_TAG:-main}"
DB_URL="postgres://sedoc:devpassword@localhost:5432/sedoc?sslmode=disable"
WEB_ROOT="/var/www/vaultdms"

INFRA="postgres redis nats minio minio-init opensearch qdrant temporal clamav"
APP="auth policy document storage search audit workflow notification signature billing \
connector mcp-server graphql-gateway collaboration intelligence intelligence-worker \
intelligence-worker-misc preview-worker temporal-ui gateway autoheal"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33m!  %s\033[0m\n' "$1"; }

PUBLIC_HOST="${PUBLIC_HOST:-$(curl -fsS http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo localhost)}"
# domain vs bare-IPv4 → decides Caddy TLS mode
if [[ "$PUBLIC_HOST" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ || "$PUBLIC_HOST" == "localhost" ]]; then
  HOST_IS_IP=1
else
  HOST_IS_IP=0
fi

# ---- 1. host dependencies --------------------------------------------------
log "Installing host dependencies"
if ! command -v docker >/dev/null; then
  apt-get update -y
  apt-get install -y ca-certificates curl git postgresql-client
  curl -fsSL https://get.docker.com | sh
fi
if ! command -v migrate >/dev/null; then
  curl -fsSL https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz \
    | tar -xz -C /usr/local/bin migrate
fi
if ! command -v go >/dev/null; then
  GO_VERSION="${GO_VERSION:-1.23.4}"
  curl -fsSL "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" | tar -xz -C /usr/local
  ln -sf /usr/local/go/bin/go /usr/local/bin/go
fi
if [ "${SKIP_WEB:-0}" != "1" ] && ! command -v node >/dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
go version

# ---- 2. kernel tuning for OpenSearch --------------------------------------
log "Setting vm.max_map_count (OpenSearch requirement)"
echo 'vm.max_map_count=262144' > /etc/sysctl.d/99-opensearch.conf
sysctl --system >/dev/null

# ---- 3. .env with fresh secrets (only if missing) --------------------------
if [ ! -f "$ENV_FILE" ]; then
  [ -f "$REPO_ROOT/.env.example" ] && cp "$REPO_ROOT/.env.example" "$ENV_FILE" || touch "$ENV_FILE"
fi
if ! grep -q SEDOC_GATEWAY_SECRET "$ENV_FILE"; then
  log "Generating .env secrets"
  ADMIN_PW="$(openssl rand -base64 18)"
  cat >> "$ENV_FILE" <<EOF

# ===== generated by bootstrap-full.sh (per-deploy) =====
SEDOC_GATEWAY_SECRET=$(openssl rand -hex 32)
SEDOC_LOCAL_KEK=$(openssl rand -hex 32)
SEDOC_ESIGN_STATE_HMAC=$(openssl rand -hex 32)
SEDOC_ONLYOFFICE_JWT=$(openssl rand -hex 32)
SEED_ADMIN_EMAIL=admin@acme.local
SEED_ADMIN_PASSWORD=${ADMIN_PW}
SEED_TENANT_SLUG=acme
SEDOC_S3_PUBLIC_BASE=${PUBLIC_HOST}:9000
SEDOC_IMAGE_TAG=${IMAGE_TAG}
SEDOC_ALLOW_BYPASS_RLS=1
EOF
  echo ">>> SEED ADMIN PASSWORD: ${ADMIN_PW}   (save this now)"
else
  log ".env already has secrets — leaving it untouched"
fi

export SEDOC_IMAGE_TAG="$IMAGE_TAG"
COMPOSE="docker compose -f docker-compose.yml -f docker-compose.prebuilt.yml"

# ---- 4. pull + start infra -------------------------------------------------
log "Pulling images (tag: $IMAGE_TAG) — this can take a few minutes"
$COMPOSE pull
log "Starting data plane + search + workflow + AV"
$COMPOSE up -d $INFRA

# ---- 5. migrate + seed (shared schema lives in document's first migration) -
log "Applying migrations + seeding admin user"
DATABASE_URL="$DB_URL" ./scripts/seed.sh

# ---- 6. start all application services + workers + gateway ----------------
log "Starting application services, workers, and gateway"
$COMPOSE up -d $APP

if [ "${ENABLE_ONLYOFFICE:-0}" = "1" ]; then
  log "Starting OnlyOffice (in-browser editing)"
  $COMPOSE up -d onlyoffice
fi

# ---- 7. build + deploy the web UI -----------------------------------------
if [ "${SKIP_WEB:-0}" != "1" ]; then
  log "Building the web UI"
  ( cd web && npm ci && npm run build )
  mkdir -p "$WEB_ROOT"
  cp -r web/dist/* "$WEB_ROOT/"
fi

# ---- 8. Caddy front door (TLS for domains, HTTP for IPs) ------------------
if [ "${SKIP_CADDY:-0}" != "1" ]; then
  log "Installing + configuring Caddy"
  if ! command -v caddy >/dev/null; then
    apt-get install -y debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
    apt-get update -y && apt-get install -y caddy
  fi

  if [ "$HOST_IS_IP" = "1" ]; then
    SITE=":80"; warn "PUBLIC_HOST is an IP/localhost — serving HTTP on :80 (no TLS). Point a domain here for HTTPS."
  else
    SITE="$PUBLIC_HOST"   # Caddy auto-provisions a Let's Encrypt cert
  fi

  cat > /etc/caddy/Caddyfile <<EOF
${SITE} {
    encode zstd gzip

    @api path /api/* /healthz
    handle @api {
        reverse_proxy localhost:8080
    }

    handle /collab/* {
        reverse_proxy localhost:8083
    }

    handle {
        root * ${WEB_ROOT}
        try_files {path} /index.html
        file_server
    }
}
EOF
  systemctl restart caddy
fi

# ---- 9. summary ------------------------------------------------------------
log "Done. Bringing up — check:  $COMPOSE ps"
if [ "$HOST_IS_IP" = "1" ]; then
  URL="http://${PUBLIC_HOST}"
else
  URL="https://${PUBLIC_HOST}"
fi
cat <<EOF

  Web UI / API:   ${URL}
  Admin login:    $(grep -E '^SEED_ADMIN_EMAIL=' "$ENV_FILE" | cut -d= -f2)
  Admin password: (printed above if just generated; else see SEED_ADMIN_PASSWORD in .env)

  Verify:
    curl -s -o /dev/null -w 'login=%{http_code}\n' -X POST ${URL}/api/v1/auth/login \\
      -H 'Content-Type: application/json' -d '{}'        # expect 401

  Uploads: presigned URLs target ${PUBLIC_HOST}:9000 (MinIO). Open port 9000 in the
  security group (your IP only) for the upload flow. For a clean all-HTTPS deployment,
  switch to real AWS S3 (see docs/deploy/ec2-full-stack.md §5).

  Heavy services (OpenSearch, ClamAV, Temporal, AI workers) take 1-2 min to report healthy.
  If OCR never runs, check:  $COMPOSE logs -f intelligence-worker
EOF
