// Generated by web/scripts/build-graphql-manifest.mjs.
// Do not hand-edit. Regenerate via: npm run graphql:manifest
//
// Each export pairs the canonicalized query text with its SHA-256
// hash so the urql persisted exchange (web/src/lib/graphql.ts) can
// post { id: hash, variables } and the backend (ADR 0074) can resolve
// the query from its embedded allow-list.

export interface PersistedOperation {
  readonly name: string
  readonly hash: string
  readonly doc: string
}

export const ActivityForDocumentQuery: PersistedOperation = {
  name: "ActivityForDocument",
  hash: "efc2ac8743fbec13e2c0aa8473d226f9b8c74b4e52a4eca6367cd4dc9086d4ef",
  doc: "query ActivityForDocument($id: ID!, $cursor: String) { activityForDocument(documentId: $id, cursor: $cursor, limit: 50) { nodes { id kind actorName summary occurredAt payload } nextCursor } }",
}

export const DocumentDetailQuery: PersistedOperation = {
  name: "DocumentDetail",
  hash: "9c331cc59050eb21403a1cbce72f7f3b3f7292d46802d887755fb92f92ddb93d",
  doc: "query DocumentDetail($id: ID!) { document(id: $id) { id tenantId workspaceId folderId title description lifecycleState regionPin documentClass classificationConfidence tags mimeType totalSizeBytes sha256Hash createdBy createdAt updatedAt customMetadata currentVersion { id versionNumber sizeBytes mimeType sha256Hash createdAt createdByName changeSummary } versions(limit: 20) { nodes { id versionNumber sizeBytes createdAt createdByName changeSummary } } comments { nodes { id body authorName authorId createdAt resolved replies { id body authorName createdAt } } } annotations { nodes { id kind page createdAt } } workflowInstances { id status definitionName startedAt tasks { id title status assigneeName dueAt } } permissions { canView canEdit canDelete canShare canAdmin } } }",
}
