{{- if .Values.preview.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vaultdms-preview-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: preview-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vaultdms-preview-worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: preview-worker
{{- end }}
