-- ADR 0068 — lightweight tasks (separate from workflow_tasks).
--
-- A task can be:
--   - user-created (source = 'user') from any document or stand-alone
--   - workflow-generated (source = 'workflow') as a follow-up to-do
--     that doesn't need an approval signal back to Temporal
--
-- The 24h-before-due + overdue reminders are tracked in-row with
-- single-shot flags so the hourly sweep stays idempotent.
CREATE TABLE IF NOT EXISTS tasks (
    tenant_id                     UUID         NOT NULL REFERENCES organizations(id),
    id                            UUID         NOT NULL DEFAULT gen_random_uuid(),
    title                         TEXT         NOT NULL,
    description                   TEXT,
    status                        TEXT         NOT NULL DEFAULT 'open'
                                       CHECK (status IN ('open','in_progress','done','cancelled')),
    priority                      TEXT         NOT NULL DEFAULT 'normal'
                                       CHECK (priority IN ('low','normal','high','urgent')),
    due_at                        TIMESTAMPTZ,
    assignee_id                   UUID,
    -- linked resources; both nullable. A task can be doc-only,
    -- workflow-only, both, or neither (a generic to-do).
    linked_document_id            UUID,
    linked_workflow_instance_id   UUID,
    -- Where the row came from. 'user' = manual create; 'workflow' =
    -- generated by a workflow step that wasn't itself an approval.
    source                        TEXT         NOT NULL DEFAULT 'user'
                                       CHECK (source IN ('user','workflow')),
    created_by                    UUID         NOT NULL,
    completed_by                  UUID,
    completed_at                  TIMESTAMPTZ,
    -- Single-shot flags so the hourly sweep emits at-most-one
    -- ping per task per state crossing.
    reminded_at                   TIMESTAMPTZ,
    overdue_notified_at           TIMESTAMPTZ,
    created_at                    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, id),
    FOREIGN KEY (tenant_id, assignee_id)        REFERENCES users(tenant_id, id) ON DELETE SET NULL,
    FOREIGN KEY (tenant_id, created_by)         REFERENCES users(tenant_id, id),
    FOREIGN KEY (tenant_id, linked_document_id) REFERENCES documents(tenant_id, id) ON DELETE SET NULL
);

-- Inbox query: every open task assigned to the caller.
CREATE INDEX IF NOT EXISTS idx_tasks_assignee_status
    ON tasks (tenant_id, assignee_id, status) WHERE assignee_id IS NOT NULL;

-- Hourly sweep: scans by status + due_at.
CREATE INDEX IF NOT EXISTS idx_tasks_sweep
    ON tasks (tenant_id, status, due_at)
    WHERE due_at IS NOT NULL AND status IN ('open','in_progress');

-- Doc-detail panel: tasks attached to a specific document.
CREATE INDEX IF NOT EXISTS idx_tasks_document
    ON tasks (tenant_id, linked_document_id)
    WHERE linked_document_id IS NOT NULL;

CREATE TRIGGER update_tasks_updated_at
    BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tasks_tenant_isolation        ON tasks;
DROP POLICY IF EXISTS tasks_tenant_isolation_insert ON tasks;
CREATE POLICY tasks_tenant_isolation ON tasks
    USING (tenant_id = current_setting('app.current_tenant', true)::uuid);
CREATE POLICY tasks_tenant_isolation_insert ON tasks
    FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);
