// Outlook add-in build pipeline (ADR 0112).
//
// Produces three HTML entries under dist/:
//   * taskpane.html     — the React app shown when the user clicks
//                          "Save to SeDoc" in the ribbon.
//   * commands.html     — Office's function-file shim. Required by
//                          the manifest's FunctionFile reference even
//                          when no UI-less commands are registered.
//   * (assets)          — icons + the manifest copied verbatim.
//
// Two modes:
//   development — webpack-dev-server with HTTPS on :3001. Office
//                  refuses to load an add-in from non-HTTPS origins,
//                  so the dev server speaks self-signed certs you
//                  trust once at setup time.
//   production  — emits a static bundle ready to upload to whatever
//                  CDN / S3 bucket / Azure Storage account hosts the
//                  add-in. See docs/howto/outlook-addin-deploy.md.

const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = (env, argv) => {
  const isProd = argv.mode === 'production'
  return {
    entry: {
      taskpane: './src/taskpane/index.tsx',
      commands: './src/commands/commands.ts',
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: '[name].[contenthash].js',
      clean: true,
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.js'],
    },
    module: {
      rules: [
        { test: /\.tsx?$/, use: 'ts-loader', exclude: /node_modules/ },
        { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      ],
    },
    plugins: [
      new HtmlWebpackPlugin({
        filename: 'taskpane.html',
        template: './src/taskpane/taskpane.html',
        chunks: ['taskpane'],
      }),
      new HtmlWebpackPlugin({
        filename: 'commands.html',
        template: './src/commands/commands.html',
        chunks: ['commands'],
      }),
      new CopyWebpackPlugin({
        patterns: [
          { from: 'manifest.xml', to: '.' },
          { from: 'assets',       to: 'assets' },
        ],
      }),
    ],
    devServer: {
      static: { directory: path.join(__dirname, 'dist') },
      port:   3001,
      hot:    true,
      // Office refuses non-HTTPS for production manifests; the dev
      // cert generated by office-addin-dev-certs lives in
      // ~/.office-addin-dev-certs. Run `npx office-addin-dev-certs install`
      // once before the first `npm run dev`.
      server: 'https',
      historyApiFallback: true,
      headers: { 'Access-Control-Allow-Origin': '*' },
    },
    devtool: isProd ? 'source-map' : 'eval-cheap-module-source-map',
  }
}
