// Outlook add-in build pipeline (ADR 0112).
//
// Produces three HTML entries under dist/:
//   * taskpane.html     — the React app shown when the user clicks
//                          "Save to SeDoc" in the ribbon.
//   * commands.html     — Office's function-file shim. Required by
//                          the manifest's FunctionFile reference even
//                          when no UI-less commands are registered.
//   * (assets)          — icons + the manifest copied verbatim.
//
// Two modes:
//   development — webpack-dev-server with HTTPS on :3001. Office
//                  refuses to load an add-in from non-HTTPS origins,
//                  so the dev server speaks self-signed certs you
//                  trust once at setup time.
//   production  — emits a static bundle ready to upload to whatever
//                  CDN / S3 bucket / Azure Storage account hosts the
//                  add-in. See docs/howto/outlook-addin-deploy.md.

const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')

// substituteManifestTokens replaces ${VAR} and ${VAR:-default} with the env
// value (or the inline default). Deployment-specific values — the Entra
// (Azure AD) client id and the bundle host — live in env, never in the repo.
// In production a token with neither an env value nor a default is a hard
// error so a store submission can't ship a literal "${...}".
function substituteManifestTokens(content, isProd) {
  const sub = (s) =>
    s.replace(/\$\{([A-Z0-9_]+)(?::-([^}]*))?\}/g, (_, name, def) => {
      const val = process.env[name]
      if (val !== undefined && val !== '') return val
      if (def !== undefined) return def
      if (isProd) {
        throw new Error(
          `manifest: ${name} is unset and has no default — set it in the build env ` +
            `(e.g. SEDOC_ADDIN_HOST, SEDOC_AAD_CLIENT_ID) before a production build`,
        )
      }
      return '' // dev: leave empty rather than a literal token
    })
  // Tokens inside XML comments are documentation — leave them verbatim.
  return content
    .split(/(<!--[\s\S]*?-->)/)
    .map((p) => (p.startsWith('<!--') ? p : sub(p)))
    .join('')
}

module.exports = (env, argv) => {
  const isProd = argv.mode === 'production'
  return {
    entry: {
      taskpane: './src/taskpane/index.tsx',
      commands: './src/commands/commands.ts',
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: '[name].[contenthash].js',
      clean: true,
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.js'],
    },
    module: {
      rules: [
        { test: /\.tsx?$/, use: 'ts-loader', exclude: /node_modules/ },
        { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      ],
    },
    plugins: [
      new HtmlWebpackPlugin({
        filename: 'taskpane.html',
        template: './src/taskpane/taskpane.html',
        chunks: ['taskpane'],
      }),
      new HtmlWebpackPlugin({
        filename: 'commands.html',
        template: './src/commands/commands.html',
        chunks: ['commands'],
      }),
      new CopyWebpackPlugin({
        patterns: [
          {
            from: 'manifest.xml',
            to: '.',
            // Substitute ${VAR} / ${VAR:-default} tokens from env at build
            // time, so no per-deployment value (Entra client id, host) is
            // committed. In production mode a token with no env value AND no
            // default fails the build rather than shipping a literal
            // "${SEDOC_AAD_CLIENT_ID}" into a store submission.
            transform(content) {
              return substituteManifestTokens(content.toString(), isProd);
            },
          },
          { from: 'assets', to: 'assets' },
        ],
      }),
    ],
    devServer: {
      static: { directory: path.join(__dirname, 'dist') },
      port:   3001,
      hot:    true,
      // Office refuses non-HTTPS for production manifests; the dev
      // cert generated by office-addin-dev-certs lives in
      // ~/.office-addin-dev-certs. Run `npx office-addin-dev-certs install`
      // once before the first `npm run dev`.
      server: 'https',
      historyApiFallback: true,
      headers: { 'Access-Control-Allow-Origin': '*' },
    },
    devtool: isProd ? 'source-map' : 'eval-cheap-module-source-map',
  }
}
