/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSavedSearchesRouteImport } from './routes/_authenticated/saved-searches'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAskRouteImport } from './routes/_authenticated/ask'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedWorkflowsDesignerRouteImport } from './routes/_authenticated/workflows/designer'
import { Route as AuthenticatedSignDoneRouteImport } from './routes/_authenticated/sign.done'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedAdminWorkflowsRouteImport } from './routes/_authenticated/admin/workflows'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSsoRouteImport } from './routes/_authenticated/admin/sso'
import { Route as AuthenticatedAdminShareLinksRouteImport } from './routes/_authenticated/admin/share-links'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRetentionRouteImport } from './routes/_authenticated/admin/retention'
import { Route as AuthenticatedAdminResidencyRouteImport } from './routes/_authenticated/admin/residency'
import { Route as AuthenticatedAdminPrivacyRouteImport } from './routes/_authenticated/admin/privacy'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminPermissionLagRouteImport } from './routes/_authenticated/admin/permission-lag'
import { Route as AuthenticatedAdminMetadataSchemaRouteImport } from './routes/_authenticated/admin/metadata-schema'
import { Route as AuthenticatedAdminLegalHoldsRouteImport } from './routes/_authenticated/admin/legal-holds'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin/integrations'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated/admin/groups'
import { Route as AuthenticatedAdminConnectorsRouteImport } from './routes/_authenticated/admin/connectors'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated/admin/compliance'
import { Route as AuthenticatedAdminBulkRouteImport } from './routes/_authenticated/admin/bulk'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedWorkflowsInstancesInstanceIdRouteImport } from './routes/_authenticated/workflows/instances/$instanceId'
import { Route as AuthenticatedSignaturesSendDocumentIdRouteImport } from './routes/_authenticated/signatures.send.$documentId'
import { Route as AuthenticatedSignInPersonRequestIdRouteImport } from './routes/_authenticated/sign.in-person.$requestId'
import { Route as AuthenticatedSignRequestIdSignerIdRouteImport } from './routes/_authenticated/sign.$requestId.$signerId'
import { Route as AuthenticatedSettingsSecurityMfaRouteImport } from './routes/_authenticated/settings/security/mfa'
import { Route as AuthenticatedAdminTenantAiRouteImport } from './routes/_authenticated/admin/tenant/ai'
import { Route as AuthenticatedAdminPlatformSupportSearchRouteImport } from './routes/_authenticated/admin/platform/support-search'
import { Route as AuthenticatedAdminIntelligenceUsageRouteImport } from './routes/_authenticated/admin/intelligence/usage'
import { Route as AuthenticatedAdminIntelligenceTagReviewRouteImport } from './routes/_authenticated/admin/intelligence/tag-review'
import { Route as AuthenticatedAdminIntelligenceRoutingRulesRouteImport } from './routes/_authenticated/admin/intelligence/routing-rules'
import { Route as AuthenticatedAdminIntelligenceOcrReviewRouteImport } from './routes/_authenticated/admin/intelligence/ocr-review'
import { Route as AuthenticatedAdminIntelligenceNerConfigRouteImport } from './routes/_authenticated/admin/intelligence/ner-config'
import { Route as AuthenticatedAdminIntelligenceModelsRouteImport } from './routes/_authenticated/admin/intelligence/models'
import { Route as AuthenticatedAdminIntelligenceFilingAnalyticsRouteImport } from './routes/_authenticated/admin/intelligence/filing-analytics'
import { Route as AuthenticatedAdminIntelligenceComplianceConfigRouteImport } from './routes/_authenticated/admin/intelligence/compliance-config'
import { Route as AuthenticatedAdminIntelligenceComplianceRouteImport } from './routes/_authenticated/admin/intelligence/compliance'
import { Route as AuthenticatedAdminIntelligenceAutoTagRouteImport } from './routes/_authenticated/admin/intelligence/auto-tag'
import { Route as AuthenticatedAdminIntelligenceAnomaliesRouteImport } from './routes/_authenticated/admin/intelligence/anomalies'
import { Route as AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/documents/$documentId'
import { Route as AuthenticatedSettingsSecurityMfaRecoveryRouteImport } from './routes/_authenticated/settings/security/mfa.recovery'
import { Route as AuthenticatedAdminTenantIdentityLdapRouteImport } from './routes/_authenticated/admin/tenant/identity/ldap'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedSearchesRoute =
  AuthenticatedSavedSearchesRouteImport.update({
    id: '/saved-searches',
    path: '/saved-searches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAskRoute = AuthenticatedAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsDesignerRoute =
  AuthenticatedWorkflowsDesignerRouteImport.update({
    id: '/workflows/designer',
    path: '/workflows/designer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignDoneRoute = AuthenticatedSignDoneRouteImport.update({
  id: '/sign/done',
  path: '/sign/done',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsRoute =
  AuthenticatedAdminWorkflowsRouteImport.update({
    id: '/admin/workflows',
    path: '/admin/workflows',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/admin/webhooks',
    path: '/admin/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSsoRoute = AuthenticatedAdminSsoRouteImport.update({
  id: '/admin/sso',
  path: '/admin/sso',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminShareLinksRoute =
  AuthenticatedAdminShareLinksRouteImport.update({
    id: '/admin/share-links',
    path: '/admin/share-links',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRetentionRoute =
  AuthenticatedAdminRetentionRouteImport.update({
    id: '/admin/retention',
    path: '/admin/retention',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminResidencyRoute =
  AuthenticatedAdminResidencyRouteImport.update({
    id: '/admin/residency',
    path: '/admin/residency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPrivacyRoute =
  AuthenticatedAdminPrivacyRouteImport.update({
    id: '/admin/privacy',
    path: '/admin/privacy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermissionLagRoute =
  AuthenticatedAdminPermissionLagRouteImport.update({
    id: '/admin/permission-lag',
    path: '/admin/permission-lag',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMetadataSchemaRoute =
  AuthenticatedAdminMetadataSchemaRouteImport.update({
    id: '/admin/metadata-schema',
    path: '/admin/metadata-schema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLegalHoldsRoute =
  AuthenticatedAdminLegalHoldsRouteImport.update({
    id: '/admin/legal-holds',
    path: '/admin/legal-holds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/admin/integrations',
    path: '/admin/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/admin/groups',
    path: '/admin/groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConnectorsRoute =
  AuthenticatedAdminConnectorsRouteImport.update({
    id: '/admin/connectors',
    path: '/admin/connectors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/admin/compliance',
    path: '/admin/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBulkRoute = AuthenticatedAdminBulkRouteImport.update({
  id: '/admin/bulk',
  path: '/admin/bulk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/admin/api-keys',
    path: '/admin/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsInstancesInstanceIdRoute =
  AuthenticatedWorkflowsInstancesInstanceIdRouteImport.update({
    id: '/workflows/instances/$instanceId',
    path: '/workflows/instances/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignaturesSendDocumentIdRoute =
  AuthenticatedSignaturesSendDocumentIdRouteImport.update({
    id: '/signatures/send/$documentId',
    path: '/signatures/send/$documentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignInPersonRequestIdRoute =
  AuthenticatedSignInPersonRequestIdRouteImport.update({
    id: '/sign/in-person/$requestId',
    path: '/sign/in-person/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignRequestIdSignerIdRoute =
  AuthenticatedSignRequestIdSignerIdRouteImport.update({
    id: '/sign/$requestId/$signerId',
    path: '/sign/$requestId/$signerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSecurityMfaRoute =
  AuthenticatedSettingsSecurityMfaRouteImport.update({
    id: '/mfa',
    path: '/mfa',
    getParentRoute: () => AuthenticatedSettingsSecurityRoute,
  } as any)
const AuthenticatedAdminTenantAiRoute =
  AuthenticatedAdminTenantAiRouteImport.update({
    id: '/admin/tenant/ai',
    path: '/admin/tenant/ai',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPlatformSupportSearchRoute =
  AuthenticatedAdminPlatformSupportSearchRouteImport.update({
    id: '/admin/platform/support-search',
    path: '/admin/platform/support-search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceUsageRoute =
  AuthenticatedAdminIntelligenceUsageRouteImport.update({
    id: '/admin/intelligence/usage',
    path: '/admin/intelligence/usage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceTagReviewRoute =
  AuthenticatedAdminIntelligenceTagReviewRouteImport.update({
    id: '/admin/intelligence/tag-review',
    path: '/admin/intelligence/tag-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceRoutingRulesRoute =
  AuthenticatedAdminIntelligenceRoutingRulesRouteImport.update({
    id: '/admin/intelligence/routing-rules',
    path: '/admin/intelligence/routing-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceOcrReviewRoute =
  AuthenticatedAdminIntelligenceOcrReviewRouteImport.update({
    id: '/admin/intelligence/ocr-review',
    path: '/admin/intelligence/ocr-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceNerConfigRoute =
  AuthenticatedAdminIntelligenceNerConfigRouteImport.update({
    id: '/admin/intelligence/ner-config',
    path: '/admin/intelligence/ner-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceModelsRoute =
  AuthenticatedAdminIntelligenceModelsRouteImport.update({
    id: '/admin/intelligence/models',
    path: '/admin/intelligence/models',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceFilingAnalyticsRoute =
  AuthenticatedAdminIntelligenceFilingAnalyticsRouteImport.update({
    id: '/admin/intelligence/filing-analytics',
    path: '/admin/intelligence/filing-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceComplianceConfigRoute =
  AuthenticatedAdminIntelligenceComplianceConfigRouteImport.update({
    id: '/admin/intelligence/compliance-config',
    path: '/admin/intelligence/compliance-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceComplianceRoute =
  AuthenticatedAdminIntelligenceComplianceRouteImport.update({
    id: '/admin/intelligence/compliance',
    path: '/admin/intelligence/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceAutoTagRoute =
  AuthenticatedAdminIntelligenceAutoTagRouteImport.update({
    id: '/admin/intelligence/auto-tag',
    path: '/admin/intelligence/auto-tag',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntelligenceAnomaliesRoute =
  AuthenticatedAdminIntelligenceAnomaliesRouteImport.update({
    id: '/admin/intelligence/anomalies',
    path: '/admin/intelligence/anomalies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute =
  AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport.update({
    id: '/workspaces/$workspaceId/documents/$documentId',
    path: '/workspaces/$workspaceId/documents/$documentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSecurityMfaRecoveryRoute =
  AuthenticatedSettingsSecurityMfaRecoveryRouteImport.update({
    id: '/recovery',
    path: '/recovery',
    getParentRoute: () => AuthenticatedSettingsSecurityMfaRoute,
  } as any)
const AuthenticatedAdminTenantIdentityLdapRoute =
  AuthenticatedAdminTenantIdentityLdapRouteImport.update({
    id: '/admin/tenant/identity/ldap',
    path: '/admin/tenant/identity/ldap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ask': typeof AuthenticatedAskRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/legal-holds': typeof AuthenticatedAdminLegalHoldsRoute
  '/admin/metadata-schema': typeof AuthenticatedAdminMetadataSchemaRoute
  '/admin/permission-lag': typeof AuthenticatedAdminPermissionLagRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/admin/residency': typeof AuthenticatedAdminResidencyRoute
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/share-links': typeof AuthenticatedAdminShareLinksRoute
  '/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRouteWithChildren
  '/sign/done': typeof AuthenticatedSignDoneRoute
  '/workflows/designer': typeof AuthenticatedWorkflowsDesignerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/admin/intelligence/anomalies': typeof AuthenticatedAdminIntelligenceAnomaliesRoute
  '/admin/intelligence/auto-tag': typeof AuthenticatedAdminIntelligenceAutoTagRoute
  '/admin/intelligence/compliance': typeof AuthenticatedAdminIntelligenceComplianceRoute
  '/admin/intelligence/compliance-config': typeof AuthenticatedAdminIntelligenceComplianceConfigRoute
  '/admin/intelligence/filing-analytics': typeof AuthenticatedAdminIntelligenceFilingAnalyticsRoute
  '/admin/intelligence/models': typeof AuthenticatedAdminIntelligenceModelsRoute
  '/admin/intelligence/ner-config': typeof AuthenticatedAdminIntelligenceNerConfigRoute
  '/admin/intelligence/ocr-review': typeof AuthenticatedAdminIntelligenceOcrReviewRoute
  '/admin/intelligence/routing-rules': typeof AuthenticatedAdminIntelligenceRoutingRulesRoute
  '/admin/intelligence/tag-review': typeof AuthenticatedAdminIntelligenceTagReviewRoute
  '/admin/intelligence/usage': typeof AuthenticatedAdminIntelligenceUsageRoute
  '/admin/platform/support-search': typeof AuthenticatedAdminPlatformSupportSearchRoute
  '/admin/tenant/ai': typeof AuthenticatedAdminTenantAiRoute
  '/settings/security/mfa': typeof AuthenticatedSettingsSecurityMfaRouteWithChildren
  '/sign/$requestId/$signerId': typeof AuthenticatedSignRequestIdSignerIdRoute
  '/sign/in-person/$requestId': typeof AuthenticatedSignInPersonRequestIdRoute
  '/signatures/send/$documentId': typeof AuthenticatedSignaturesSendDocumentIdRoute
  '/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/admin/tenant/identity/ldap': typeof AuthenticatedAdminTenantIdentityLdapRoute
  '/settings/security/mfa/recovery': typeof AuthenticatedSettingsSecurityMfaRecoveryRoute
  '/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ask': typeof AuthenticatedAskRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/shared/$token': typeof SharedTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/legal-holds': typeof AuthenticatedAdminLegalHoldsRoute
  '/admin/metadata-schema': typeof AuthenticatedAdminMetadataSchemaRoute
  '/admin/permission-lag': typeof AuthenticatedAdminPermissionLagRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/admin/residency': typeof AuthenticatedAdminResidencyRoute
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/share-links': typeof AuthenticatedAdminShareLinksRoute
  '/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRouteWithChildren
  '/sign/done': typeof AuthenticatedSignDoneRoute
  '/workflows/designer': typeof AuthenticatedWorkflowsDesignerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/admin/intelligence/anomalies': typeof AuthenticatedAdminIntelligenceAnomaliesRoute
  '/admin/intelligence/auto-tag': typeof AuthenticatedAdminIntelligenceAutoTagRoute
  '/admin/intelligence/compliance': typeof AuthenticatedAdminIntelligenceComplianceRoute
  '/admin/intelligence/compliance-config': typeof AuthenticatedAdminIntelligenceComplianceConfigRoute
  '/admin/intelligence/filing-analytics': typeof AuthenticatedAdminIntelligenceFilingAnalyticsRoute
  '/admin/intelligence/models': typeof AuthenticatedAdminIntelligenceModelsRoute
  '/admin/intelligence/ner-config': typeof AuthenticatedAdminIntelligenceNerConfigRoute
  '/admin/intelligence/ocr-review': typeof AuthenticatedAdminIntelligenceOcrReviewRoute
  '/admin/intelligence/routing-rules': typeof AuthenticatedAdminIntelligenceRoutingRulesRoute
  '/admin/intelligence/tag-review': typeof AuthenticatedAdminIntelligenceTagReviewRoute
  '/admin/intelligence/usage': typeof AuthenticatedAdminIntelligenceUsageRoute
  '/admin/platform/support-search': typeof AuthenticatedAdminPlatformSupportSearchRoute
  '/admin/tenant/ai': typeof AuthenticatedAdminTenantAiRoute
  '/settings/security/mfa': typeof AuthenticatedSettingsSecurityMfaRouteWithChildren
  '/sign/$requestId/$signerId': typeof AuthenticatedSignRequestIdSignerIdRoute
  '/sign/in-person/$requestId': typeof AuthenticatedSignInPersonRequestIdRoute
  '/signatures/send/$documentId': typeof AuthenticatedSignaturesSendDocumentIdRoute
  '/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/admin/tenant/identity/ldap': typeof AuthenticatedAdminTenantIdentityLdapRoute
  '/settings/security/mfa/recovery': typeof AuthenticatedSettingsSecurityMfaRecoveryRoute
  '/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/ask': typeof AuthenticatedAskRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/saved-searches': typeof AuthenticatedSavedSearchesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/legal-holds': typeof AuthenticatedAdminLegalHoldsRoute
  '/_authenticated/admin/metadata-schema': typeof AuthenticatedAdminMetadataSchemaRoute
  '/_authenticated/admin/permission-lag': typeof AuthenticatedAdminPermissionLagRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/_authenticated/admin/residency': typeof AuthenticatedAdminResidencyRoute
  '/_authenticated/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/share-links': typeof AuthenticatedAdminShareLinksRoute
  '/_authenticated/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRouteWithChildren
  '/_authenticated/sign/done': typeof AuthenticatedSignDoneRoute
  '/_authenticated/workflows/designer': typeof AuthenticatedWorkflowsDesignerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/admin/intelligence/anomalies': typeof AuthenticatedAdminIntelligenceAnomaliesRoute
  '/_authenticated/admin/intelligence/auto-tag': typeof AuthenticatedAdminIntelligenceAutoTagRoute
  '/_authenticated/admin/intelligence/compliance': typeof AuthenticatedAdminIntelligenceComplianceRoute
  '/_authenticated/admin/intelligence/compliance-config': typeof AuthenticatedAdminIntelligenceComplianceConfigRoute
  '/_authenticated/admin/intelligence/filing-analytics': typeof AuthenticatedAdminIntelligenceFilingAnalyticsRoute
  '/_authenticated/admin/intelligence/models': typeof AuthenticatedAdminIntelligenceModelsRoute
  '/_authenticated/admin/intelligence/ner-config': typeof AuthenticatedAdminIntelligenceNerConfigRoute
  '/_authenticated/admin/intelligence/ocr-review': typeof AuthenticatedAdminIntelligenceOcrReviewRoute
  '/_authenticated/admin/intelligence/routing-rules': typeof AuthenticatedAdminIntelligenceRoutingRulesRoute
  '/_authenticated/admin/intelligence/tag-review': typeof AuthenticatedAdminIntelligenceTagReviewRoute
  '/_authenticated/admin/intelligence/usage': typeof AuthenticatedAdminIntelligenceUsageRoute
  '/_authenticated/admin/platform/support-search': typeof AuthenticatedAdminPlatformSupportSearchRoute
  '/_authenticated/admin/tenant/ai': typeof AuthenticatedAdminTenantAiRoute
  '/_authenticated/settings/security/mfa': typeof AuthenticatedSettingsSecurityMfaRouteWithChildren
  '/_authenticated/sign/$requestId/$signerId': typeof AuthenticatedSignRequestIdSignerIdRoute
  '/_authenticated/sign/in-person/$requestId': typeof AuthenticatedSignInPersonRequestIdRoute
  '/_authenticated/signatures/send/$documentId': typeof AuthenticatedSignaturesSendDocumentIdRoute
  '/_authenticated/workflows/instances/$instanceId': typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/admin/tenant/identity/ldap': typeof AuthenticatedAdminTenantIdentityLdapRoute
  '/_authenticated/settings/security/mfa/recovery': typeof AuthenticatedSettingsSecurityMfaRecoveryRoute
  '/_authenticated/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ask'
    | '/notifications'
    | '/saved-searches'
    | '/search'
    | '/tasks'
    | '/trash'
    | '/shared/$token'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/bulk'
    | '/admin/compliance'
    | '/admin/connectors'
    | '/admin/groups'
    | '/admin/integrations'
    | '/admin/legal-holds'
    | '/admin/metadata-schema'
    | '/admin/permission-lag'
    | '/admin/permissions'
    | '/admin/privacy'
    | '/admin/residency'
    | '/admin/retention'
    | '/admin/settings'
    | '/admin/share-links'
    | '/admin/sso'
    | '/admin/tags'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/settings/notifications'
    | '/settings/security'
    | '/sign/done'
    | '/workflows/designer'
    | '/admin/'
    | '/workspaces/'
    | '/admin/intelligence/anomalies'
    | '/admin/intelligence/auto-tag'
    | '/admin/intelligence/compliance'
    | '/admin/intelligence/compliance-config'
    | '/admin/intelligence/filing-analytics'
    | '/admin/intelligence/models'
    | '/admin/intelligence/ner-config'
    | '/admin/intelligence/ocr-review'
    | '/admin/intelligence/routing-rules'
    | '/admin/intelligence/tag-review'
    | '/admin/intelligence/usage'
    | '/admin/platform/support-search'
    | '/admin/tenant/ai'
    | '/settings/security/mfa'
    | '/sign/$requestId/$signerId'
    | '/sign/in-person/$requestId'
    | '/signatures/send/$documentId'
    | '/workflows/instances/$instanceId'
    | '/workspaces/$workspaceId/'
    | '/admin/tenant/identity/ldap'
    | '/settings/security/mfa/recovery'
    | '/workspaces/$workspaceId/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/ask'
    | '/notifications'
    | '/saved-searches'
    | '/search'
    | '/tasks'
    | '/trash'
    | '/shared/$token'
    | '/'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/bulk'
    | '/admin/compliance'
    | '/admin/connectors'
    | '/admin/groups'
    | '/admin/integrations'
    | '/admin/legal-holds'
    | '/admin/metadata-schema'
    | '/admin/permission-lag'
    | '/admin/permissions'
    | '/admin/privacy'
    | '/admin/residency'
    | '/admin/retention'
    | '/admin/settings'
    | '/admin/share-links'
    | '/admin/sso'
    | '/admin/tags'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/settings/notifications'
    | '/settings/security'
    | '/sign/done'
    | '/workflows/designer'
    | '/admin'
    | '/workspaces'
    | '/admin/intelligence/anomalies'
    | '/admin/intelligence/auto-tag'
    | '/admin/intelligence/compliance'
    | '/admin/intelligence/compliance-config'
    | '/admin/intelligence/filing-analytics'
    | '/admin/intelligence/models'
    | '/admin/intelligence/ner-config'
    | '/admin/intelligence/ocr-review'
    | '/admin/intelligence/routing-rules'
    | '/admin/intelligence/tag-review'
    | '/admin/intelligence/usage'
    | '/admin/platform/support-search'
    | '/admin/tenant/ai'
    | '/settings/security/mfa'
    | '/sign/$requestId/$signerId'
    | '/sign/in-person/$requestId'
    | '/signatures/send/$documentId'
    | '/workflows/instances/$instanceId'
    | '/workspaces/$workspaceId'
    | '/admin/tenant/identity/ldap'
    | '/settings/security/mfa/recovery'
    | '/workspaces/$workspaceId/documents/$documentId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authenticated/ask'
    | '/_authenticated/notifications'
    | '/_authenticated/saved-searches'
    | '/_authenticated/search'
    | '/_authenticated/tasks'
    | '/_authenticated/trash'
    | '/shared/$token'
    | '/_authenticated/'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/bulk'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/connectors'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/legal-holds'
    | '/_authenticated/admin/metadata-schema'
    | '/_authenticated/admin/permission-lag'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/privacy'
    | '/_authenticated/admin/residency'
    | '/_authenticated/admin/retention'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/share-links'
    | '/_authenticated/admin/sso'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/admin/workflows'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/security'
    | '/_authenticated/sign/done'
    | '/_authenticated/workflows/designer'
    | '/_authenticated/admin/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/admin/intelligence/anomalies'
    | '/_authenticated/admin/intelligence/auto-tag'
    | '/_authenticated/admin/intelligence/compliance'
    | '/_authenticated/admin/intelligence/compliance-config'
    | '/_authenticated/admin/intelligence/filing-analytics'
    | '/_authenticated/admin/intelligence/models'
    | '/_authenticated/admin/intelligence/ner-config'
    | '/_authenticated/admin/intelligence/ocr-review'
    | '/_authenticated/admin/intelligence/routing-rules'
    | '/_authenticated/admin/intelligence/tag-review'
    | '/_authenticated/admin/intelligence/usage'
    | '/_authenticated/admin/platform/support-search'
    | '/_authenticated/admin/tenant/ai'
    | '/_authenticated/settings/security/mfa'
    | '/_authenticated/sign/$requestId/$signerId'
    | '/_authenticated/sign/in-person/$requestId'
    | '/_authenticated/signatures/send/$documentId'
    | '/_authenticated/workflows/instances/$instanceId'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/admin/tenant/identity/ldap'
    | '/_authenticated/settings/security/mfa/recovery'
    | '/_authenticated/workspaces/$workspaceId/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved-searches': {
      id: '/_authenticated/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof AuthenticatedSavedSearchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask': {
      id: '/_authenticated/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/designer': {
      id: '/_authenticated/workflows/designer'
      path: '/workflows/designer'
      fullPath: '/workflows/designer'
      preLoaderRoute: typeof AuthenticatedWorkflowsDesignerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sign/done': {
      id: '/_authenticated/sign/done'
      path: '/sign/done'
      fullPath: '/sign/done'
      preLoaderRoute: typeof AuthenticatedSignDoneRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows': {
      id: '/_authenticated/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/sso': {
      id: '/_authenticated/admin/sso'
      path: '/admin/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AuthenticatedAdminSsoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/share-links': {
      id: '/_authenticated/admin/share-links'
      path: '/admin/share-links'
      fullPath: '/admin/share-links'
      preLoaderRoute: typeof AuthenticatedAdminShareLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/retention': {
      id: '/_authenticated/admin/retention'
      path: '/admin/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AuthenticatedAdminRetentionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/residency': {
      id: '/_authenticated/admin/residency'
      path: '/admin/residency'
      fullPath: '/admin/residency'
      preLoaderRoute: typeof AuthenticatedAdminResidencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/privacy': {
      id: '/_authenticated/admin/privacy'
      path: '/admin/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AuthenticatedAdminPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permission-lag': {
      id: '/_authenticated/admin/permission-lag'
      path: '/admin/permission-lag'
      fullPath: '/admin/permission-lag'
      preLoaderRoute: typeof AuthenticatedAdminPermissionLagRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/metadata-schema': {
      id: '/_authenticated/admin/metadata-schema'
      path: '/admin/metadata-schema'
      fullPath: '/admin/metadata-schema'
      preLoaderRoute: typeof AuthenticatedAdminMetadataSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/legal-holds': {
      id: '/_authenticated/admin/legal-holds'
      path: '/admin/legal-holds'
      fullPath: '/admin/legal-holds'
      preLoaderRoute: typeof AuthenticatedAdminLegalHoldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/connectors': {
      id: '/_authenticated/admin/connectors'
      path: '/admin/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AuthenticatedAdminConnectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/bulk': {
      id: '/_authenticated/admin/bulk'
      path: '/admin/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AuthenticatedAdminBulkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/instances/$instanceId': {
      id: '/_authenticated/workflows/instances/$instanceId'
      path: '/workflows/instances/$instanceId'
      fullPath: '/workflows/instances/$instanceId'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signatures/send/$documentId': {
      id: '/_authenticated/signatures/send/$documentId'
      path: '/signatures/send/$documentId'
      fullPath: '/signatures/send/$documentId'
      preLoaderRoute: typeof AuthenticatedSignaturesSendDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sign/in-person/$requestId': {
      id: '/_authenticated/sign/in-person/$requestId'
      path: '/sign/in-person/$requestId'
      fullPath: '/sign/in-person/$requestId'
      preLoaderRoute: typeof AuthenticatedSignInPersonRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sign/$requestId/$signerId': {
      id: '/_authenticated/sign/$requestId/$signerId'
      path: '/sign/$requestId/$signerId'
      fullPath: '/sign/$requestId/$signerId'
      preLoaderRoute: typeof AuthenticatedSignRequestIdSignerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security/mfa': {
      id: '/_authenticated/settings/security/mfa'
      path: '/mfa'
      fullPath: '/settings/security/mfa'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityMfaRouteImport
      parentRoute: typeof AuthenticatedSettingsSecurityRoute
    }
    '/_authenticated/admin/tenant/ai': {
      id: '/_authenticated/admin/tenant/ai'
      path: '/admin/tenant/ai'
      fullPath: '/admin/tenant/ai'
      preLoaderRoute: typeof AuthenticatedAdminTenantAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/platform/support-search': {
      id: '/_authenticated/admin/platform/support-search'
      path: '/admin/platform/support-search'
      fullPath: '/admin/platform/support-search'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSupportSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/usage': {
      id: '/_authenticated/admin/intelligence/usage'
      path: '/admin/intelligence/usage'
      fullPath: '/admin/intelligence/usage'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/tag-review': {
      id: '/_authenticated/admin/intelligence/tag-review'
      path: '/admin/intelligence/tag-review'
      fullPath: '/admin/intelligence/tag-review'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceTagReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/routing-rules': {
      id: '/_authenticated/admin/intelligence/routing-rules'
      path: '/admin/intelligence/routing-rules'
      fullPath: '/admin/intelligence/routing-rules'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceRoutingRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/ocr-review': {
      id: '/_authenticated/admin/intelligence/ocr-review'
      path: '/admin/intelligence/ocr-review'
      fullPath: '/admin/intelligence/ocr-review'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceOcrReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/ner-config': {
      id: '/_authenticated/admin/intelligence/ner-config'
      path: '/admin/intelligence/ner-config'
      fullPath: '/admin/intelligence/ner-config'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceNerConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/models': {
      id: '/_authenticated/admin/intelligence/models'
      path: '/admin/intelligence/models'
      fullPath: '/admin/intelligence/models'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/filing-analytics': {
      id: '/_authenticated/admin/intelligence/filing-analytics'
      path: '/admin/intelligence/filing-analytics'
      fullPath: '/admin/intelligence/filing-analytics'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceFilingAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/compliance-config': {
      id: '/_authenticated/admin/intelligence/compliance-config'
      path: '/admin/intelligence/compliance-config'
      fullPath: '/admin/intelligence/compliance-config'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceComplianceConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/compliance': {
      id: '/_authenticated/admin/intelligence/compliance'
      path: '/admin/intelligence/compliance'
      fullPath: '/admin/intelligence/compliance'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/auto-tag': {
      id: '/_authenticated/admin/intelligence/auto-tag'
      path: '/admin/intelligence/auto-tag'
      fullPath: '/admin/intelligence/auto-tag'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceAutoTagRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/intelligence/anomalies': {
      id: '/_authenticated/admin/intelligence/anomalies'
      path: '/admin/intelligence/anomalies'
      fullPath: '/admin/intelligence/anomalies'
      preLoaderRoute: typeof AuthenticatedAdminIntelligenceAnomaliesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/documents/$documentId': {
      id: '/_authenticated/workspaces/$workspaceId/documents/$documentId'
      path: '/workspaces/$workspaceId/documents/$documentId'
      fullPath: '/workspaces/$workspaceId/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/security/mfa/recovery': {
      id: '/_authenticated/settings/security/mfa/recovery'
      path: '/recovery'
      fullPath: '/settings/security/mfa/recovery'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityMfaRecoveryRouteImport
      parentRoute: typeof AuthenticatedSettingsSecurityMfaRoute
    }
    '/_authenticated/admin/tenant/identity/ldap': {
      id: '/_authenticated/admin/tenant/identity/ldap'
      path: '/admin/tenant/identity/ldap'
      fullPath: '/admin/tenant/identity/ldap'
      preLoaderRoute: typeof AuthenticatedAdminTenantIdentityLdapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsSecurityMfaRouteChildren {
  AuthenticatedSettingsSecurityMfaRecoveryRoute: typeof AuthenticatedSettingsSecurityMfaRecoveryRoute
}

const AuthenticatedSettingsSecurityMfaRouteChildren: AuthenticatedSettingsSecurityMfaRouteChildren =
  {
    AuthenticatedSettingsSecurityMfaRecoveryRoute:
      AuthenticatedSettingsSecurityMfaRecoveryRoute,
  }

const AuthenticatedSettingsSecurityMfaRouteWithChildren =
  AuthenticatedSettingsSecurityMfaRoute._addFileChildren(
    AuthenticatedSettingsSecurityMfaRouteChildren,
  )

interface AuthenticatedSettingsSecurityRouteChildren {
  AuthenticatedSettingsSecurityMfaRoute: typeof AuthenticatedSettingsSecurityMfaRouteWithChildren
}

const AuthenticatedSettingsSecurityRouteChildren: AuthenticatedSettingsSecurityRouteChildren =
  {
    AuthenticatedSettingsSecurityMfaRoute:
      AuthenticatedSettingsSecurityMfaRouteWithChildren,
  }

const AuthenticatedSettingsSecurityRouteWithChildren =
  AuthenticatedSettingsSecurityRoute._addFileChildren(
    AuthenticatedSettingsSecurityRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAskRoute: typeof AuthenticatedAskRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSavedSearchesRoute: typeof AuthenticatedSavedSearchesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminBulkRoute: typeof AuthenticatedAdminBulkRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminConnectorsRoute: typeof AuthenticatedAdminConnectorsRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminLegalHoldsRoute: typeof AuthenticatedAdminLegalHoldsRoute
  AuthenticatedAdminMetadataSchemaRoute: typeof AuthenticatedAdminMetadataSchemaRoute
  AuthenticatedAdminPermissionLagRoute: typeof AuthenticatedAdminPermissionLagRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPrivacyRoute: typeof AuthenticatedAdminPrivacyRoute
  AuthenticatedAdminResidencyRoute: typeof AuthenticatedAdminResidencyRoute
  AuthenticatedAdminRetentionRoute: typeof AuthenticatedAdminRetentionRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShareLinksRoute: typeof AuthenticatedAdminShareLinksRoute
  AuthenticatedAdminSsoRoute: typeof AuthenticatedAdminSsoRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminWorkflowsRoute: typeof AuthenticatedAdminWorkflowsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRouteWithChildren
  AuthenticatedSignDoneRoute: typeof AuthenticatedSignDoneRoute
  AuthenticatedWorkflowsDesignerRoute: typeof AuthenticatedWorkflowsDesignerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedAdminIntelligenceAnomaliesRoute: typeof AuthenticatedAdminIntelligenceAnomaliesRoute
  AuthenticatedAdminIntelligenceAutoTagRoute: typeof AuthenticatedAdminIntelligenceAutoTagRoute
  AuthenticatedAdminIntelligenceComplianceRoute: typeof AuthenticatedAdminIntelligenceComplianceRoute
  AuthenticatedAdminIntelligenceComplianceConfigRoute: typeof AuthenticatedAdminIntelligenceComplianceConfigRoute
  AuthenticatedAdminIntelligenceFilingAnalyticsRoute: typeof AuthenticatedAdminIntelligenceFilingAnalyticsRoute
  AuthenticatedAdminIntelligenceModelsRoute: typeof AuthenticatedAdminIntelligenceModelsRoute
  AuthenticatedAdminIntelligenceNerConfigRoute: typeof AuthenticatedAdminIntelligenceNerConfigRoute
  AuthenticatedAdminIntelligenceOcrReviewRoute: typeof AuthenticatedAdminIntelligenceOcrReviewRoute
  AuthenticatedAdminIntelligenceRoutingRulesRoute: typeof AuthenticatedAdminIntelligenceRoutingRulesRoute
  AuthenticatedAdminIntelligenceTagReviewRoute: typeof AuthenticatedAdminIntelligenceTagReviewRoute
  AuthenticatedAdminIntelligenceUsageRoute: typeof AuthenticatedAdminIntelligenceUsageRoute
  AuthenticatedAdminPlatformSupportSearchRoute: typeof AuthenticatedAdminPlatformSupportSearchRoute
  AuthenticatedAdminTenantAiRoute: typeof AuthenticatedAdminTenantAiRoute
  AuthenticatedSignRequestIdSignerIdRoute: typeof AuthenticatedSignRequestIdSignerIdRoute
  AuthenticatedSignInPersonRequestIdRoute: typeof AuthenticatedSignInPersonRequestIdRoute
  AuthenticatedSignaturesSendDocumentIdRoute: typeof AuthenticatedSignaturesSendDocumentIdRoute
  AuthenticatedWorkflowsInstancesInstanceIdRoute: typeof AuthenticatedWorkflowsInstancesInstanceIdRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  AuthenticatedAdminTenantIdentityLdapRoute: typeof AuthenticatedAdminTenantIdentityLdapRoute
  AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAskRoute: AuthenticatedAskRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSavedSearchesRoute: AuthenticatedSavedSearchesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminBulkRoute: AuthenticatedAdminBulkRoute,
  AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
  AuthenticatedAdminConnectorsRoute: AuthenticatedAdminConnectorsRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminLegalHoldsRoute: AuthenticatedAdminLegalHoldsRoute,
  AuthenticatedAdminMetadataSchemaRoute: AuthenticatedAdminMetadataSchemaRoute,
  AuthenticatedAdminPermissionLagRoute: AuthenticatedAdminPermissionLagRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPrivacyRoute: AuthenticatedAdminPrivacyRoute,
  AuthenticatedAdminResidencyRoute: AuthenticatedAdminResidencyRoute,
  AuthenticatedAdminRetentionRoute: AuthenticatedAdminRetentionRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminShareLinksRoute: AuthenticatedAdminShareLinksRoute,
  AuthenticatedAdminSsoRoute: AuthenticatedAdminSsoRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminWorkflowsRoute: AuthenticatedAdminWorkflowsRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsSecurityRoute:
    AuthenticatedSettingsSecurityRouteWithChildren,
  AuthenticatedSignDoneRoute: AuthenticatedSignDoneRoute,
  AuthenticatedWorkflowsDesignerRoute: AuthenticatedWorkflowsDesignerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedAdminIntelligenceAnomaliesRoute:
    AuthenticatedAdminIntelligenceAnomaliesRoute,
  AuthenticatedAdminIntelligenceAutoTagRoute:
    AuthenticatedAdminIntelligenceAutoTagRoute,
  AuthenticatedAdminIntelligenceComplianceRoute:
    AuthenticatedAdminIntelligenceComplianceRoute,
  AuthenticatedAdminIntelligenceComplianceConfigRoute:
    AuthenticatedAdminIntelligenceComplianceConfigRoute,
  AuthenticatedAdminIntelligenceFilingAnalyticsRoute:
    AuthenticatedAdminIntelligenceFilingAnalyticsRoute,
  AuthenticatedAdminIntelligenceModelsRoute:
    AuthenticatedAdminIntelligenceModelsRoute,
  AuthenticatedAdminIntelligenceNerConfigRoute:
    AuthenticatedAdminIntelligenceNerConfigRoute,
  AuthenticatedAdminIntelligenceOcrReviewRoute:
    AuthenticatedAdminIntelligenceOcrReviewRoute,
  AuthenticatedAdminIntelligenceRoutingRulesRoute:
    AuthenticatedAdminIntelligenceRoutingRulesRoute,
  AuthenticatedAdminIntelligenceTagReviewRoute:
    AuthenticatedAdminIntelligenceTagReviewRoute,
  AuthenticatedAdminIntelligenceUsageRoute:
    AuthenticatedAdminIntelligenceUsageRoute,
  AuthenticatedAdminPlatformSupportSearchRoute:
    AuthenticatedAdminPlatformSupportSearchRoute,
  AuthenticatedAdminTenantAiRoute: AuthenticatedAdminTenantAiRoute,
  AuthenticatedSignRequestIdSignerIdRoute:
    AuthenticatedSignRequestIdSignerIdRoute,
  AuthenticatedSignInPersonRequestIdRoute:
    AuthenticatedSignInPersonRequestIdRoute,
  AuthenticatedSignaturesSendDocumentIdRoute:
    AuthenticatedSignaturesSendDocumentIdRoute,
  AuthenticatedWorkflowsInstancesInstanceIdRoute:
    AuthenticatedWorkflowsInstancesInstanceIdRoute,
  AuthenticatedWorkspacesWorkspaceIdIndexRoute:
    AuthenticatedWorkspacesWorkspaceIdIndexRoute,
  AuthenticatedAdminTenantIdentityLdapRoute:
    AuthenticatedAdminTenantIdentityLdapRoute,
  AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute:
    AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
