/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DsrStatusRouteImport } from './routes/dsr-status'
import { Route as DsrRequestRouteImport } from './routes/dsr-request'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedAcknowledgementsRouteImport } from './routes/_authenticated/acknowledgements'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedWorkflowsInstanceIdRouteImport } from './routes/_authenticated/workflows/$instanceId'
import { Route as AuthenticatedSettingsSignaturesRouteImport } from './routes/_authenticated/settings/signatures'
import { Route as AuthenticatedSettingsSessionsRouteImport } from './routes/_authenticated/settings/sessions'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedLegalHoldsMyRouteImport } from './routes/_authenticated/legal-holds/my'
import { Route as AuthenticatedAdminWorkflowsRouteImport } from './routes/_authenticated/admin/workflows'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin/tenants'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSsoRouteImport } from './routes/_authenticated/admin/sso'
import { Route as AuthenticatedAdminShareLinksRouteImport } from './routes/_authenticated/admin/share-links'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRetentionRouteImport } from './routes/_authenticated/admin/retention'
import { Route as AuthenticatedAdminResidencyRouteImport } from './routes/_authenticated/admin/residency'
import { Route as AuthenticatedAdminQuarantineRouteImport } from './routes/_authenticated/admin/quarantine'
import { Route as AuthenticatedAdminPrivacyRouteImport } from './routes/_authenticated/admin/privacy'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminMetadataSchemaRouteImport } from './routes/_authenticated/admin/metadata-schema'
import { Route as AuthenticatedAdminLegalHoldsRouteImport } from './routes/_authenticated/admin/legal-holds'
import { Route as AuthenticatedAdminGroupsRouteImport } from './routes/_authenticated/admin/groups'
import { Route as AuthenticatedAdminGeofencesRouteImport } from './routes/_authenticated/admin/geofences'
import { Route as AuthenticatedAdminDispositionRouteImport } from './routes/_authenticated/admin/disposition'
import { Route as AuthenticatedAdminConnectorsRouteImport } from './routes/_authenticated/admin/connectors'
import { Route as AuthenticatedAdminComplianceRouteImport } from './routes/_authenticated/admin/compliance'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin/billing'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAdminAcknowledgementsRouteImport } from './routes/_authenticated/admin/acknowledgements'
import { Route as AuthenticatedWorkspacesWorkspaceIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceId/index'
import { Route as AuthenticatedAdminTenantSecurityRouteImport } from './routes/_authenticated/admin/tenant/security'
import { Route as AuthenticatedAdminTenantResidencyRouteImport } from './routes/_authenticated/admin/tenant/residency'
import { Route as AuthenticatedAdminPlatformSecurityRouteImport } from './routes/_authenticated/admin/platform/security'
import { Route as AuthenticatedAdminPlatformSchedulesRouteImport } from './routes/_authenticated/admin/platform/schedules'
import { Route as AuthenticatedAdminPlatformInternalAuthRouteImport } from './routes/_authenticated/admin/platform/internal-auth'
import { Route as AuthenticatedAdminAcknowledgementsCampaignIdRouteImport } from './routes/_authenticated/admin/acknowledgements/$campaignId'
import { Route as AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport } from './routes/_authenticated/workspaces/$workspaceId/documents/$documentId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DsrStatusRoute = DsrStatusRouteImport.update({
  id: '/dsr-status',
  path: '/dsr-status',
  getParentRoute: () => rootRouteImport,
} as any)
const DsrRequestRoute = DsrRequestRouteImport.update({
  id: '/dsr-request',
  path: '/dsr-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAcknowledgementsRoute =
  AuthenticatedAcknowledgementsRouteImport.update({
    id: '/acknowledgements',
    path: '/acknowledgements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsInstanceIdRoute =
  AuthenticatedWorkflowsInstanceIdRouteImport.update({
    id: '/workflows/$instanceId',
    path: '/workflows/$instanceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSignaturesRoute =
  AuthenticatedSettingsSignaturesRouteImport.update({
    id: '/signatures',
    path: '/signatures',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSessionsRoute =
  AuthenticatedSettingsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedLegalHoldsMyRoute =
  AuthenticatedLegalHoldsMyRouteImport.update({
    id: '/legal-holds/my',
    path: '/legal-holds/my',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkflowsRoute =
  AuthenticatedAdminWorkflowsRouteImport.update({
    id: '/admin/workflows',
    path: '/admin/workflows',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/admin/webhooks',
    path: '/admin/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/admin/tags',
  path: '/admin/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSsoRoute = AuthenticatedAdminSsoRouteImport.update({
  id: '/admin/sso',
  path: '/admin/sso',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminShareLinksRoute =
  AuthenticatedAdminShareLinksRouteImport.update({
    id: '/admin/share-links',
    path: '/admin/share-links',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRetentionRoute =
  AuthenticatedAdminRetentionRouteImport.update({
    id: '/admin/retention',
    path: '/admin/retention',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminResidencyRoute =
  AuthenticatedAdminResidencyRouteImport.update({
    id: '/admin/residency',
    path: '/admin/residency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuarantineRoute =
  AuthenticatedAdminQuarantineRouteImport.update({
    id: '/admin/quarantine',
    path: '/admin/quarantine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPrivacyRoute =
  AuthenticatedAdminPrivacyRouteImport.update({
    id: '/admin/privacy',
    path: '/admin/privacy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMetadataSchemaRoute =
  AuthenticatedAdminMetadataSchemaRouteImport.update({
    id: '/admin/metadata-schema',
    path: '/admin/metadata-schema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLegalHoldsRoute =
  AuthenticatedAdminLegalHoldsRouteImport.update({
    id: '/admin/legal-holds',
    path: '/admin/legal-holds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGroupsRoute =
  AuthenticatedAdminGroupsRouteImport.update({
    id: '/admin/groups',
    path: '/admin/groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGeofencesRoute =
  AuthenticatedAdminGeofencesRouteImport.update({
    id: '/admin/geofences',
    path: '/admin/geofences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDispositionRoute =
  AuthenticatedAdminDispositionRouteImport.update({
    id: '/admin/disposition',
    path: '/admin/disposition',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminConnectorsRoute =
  AuthenticatedAdminConnectorsRouteImport.update({
    id: '/admin/connectors',
    path: '/admin/connectors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminComplianceRoute =
  AuthenticatedAdminComplianceRouteImport.update({
    id: '/admin/compliance',
    path: '/admin/compliance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin/billing',
    path: '/admin/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/admin/api-keys',
    path: '/admin/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAcknowledgementsRoute =
  AuthenticatedAdminAcknowledgementsRouteImport.update({
    id: '/admin/acknowledgements',
    path: '/admin/acknowledgements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/',
    path: '/workspaces/$workspaceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTenantSecurityRoute =
  AuthenticatedAdminTenantSecurityRouteImport.update({
    id: '/admin/tenant/security',
    path: '/admin/tenant/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminTenantResidencyRoute =
  AuthenticatedAdminTenantResidencyRouteImport.update({
    id: '/admin/tenant/residency',
    path: '/admin/tenant/residency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPlatformSecurityRoute =
  AuthenticatedAdminPlatformSecurityRouteImport.update({
    id: '/admin/platform/security',
    path: '/admin/platform/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPlatformSchedulesRoute =
  AuthenticatedAdminPlatformSchedulesRouteImport.update({
    id: '/admin/platform/schedules',
    path: '/admin/platform/schedules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPlatformInternalAuthRoute =
  AuthenticatedAdminPlatformInternalAuthRouteImport.update({
    id: '/admin/platform/internal-auth',
    path: '/admin/platform/internal-auth',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAcknowledgementsCampaignIdRoute =
  AuthenticatedAdminAcknowledgementsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AuthenticatedAdminAcknowledgementsRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute =
  AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport.update({
    id: '/workspaces/$workspaceId/documents/$documentId',
    path: '/workspaces/$workspaceId/documents/$documentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dsr-request': typeof DsrRequestRoute
  '/dsr-status': typeof DsrStatusRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/acknowledgements': typeof AuthenticatedAcknowledgementsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/acknowledgements': typeof AuthenticatedAdminAcknowledgementsRouteWithChildren
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/admin/disposition': typeof AuthenticatedAdminDispositionRoute
  '/admin/geofences': typeof AuthenticatedAdminGeofencesRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/legal-holds': typeof AuthenticatedAdminLegalHoldsRoute
  '/admin/metadata-schema': typeof AuthenticatedAdminMetadataSchemaRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/admin/quarantine': typeof AuthenticatedAdminQuarantineRoute
  '/admin/residency': typeof AuthenticatedAdminResidencyRoute
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/share-links': typeof AuthenticatedAdminShareLinksRoute
  '/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/legal-holds/my': typeof AuthenticatedLegalHoldsMyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/sessions': typeof AuthenticatedSettingsSessionsRoute
  '/settings/signatures': typeof AuthenticatedSettingsSignaturesRoute
  '/workflows/$instanceId': typeof AuthenticatedWorkflowsInstanceIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/admin/acknowledgements/$campaignId': typeof AuthenticatedAdminAcknowledgementsCampaignIdRoute
  '/admin/platform/internal-auth': typeof AuthenticatedAdminPlatformInternalAuthRoute
  '/admin/platform/schedules': typeof AuthenticatedAdminPlatformSchedulesRoute
  '/admin/platform/security': typeof AuthenticatedAdminPlatformSecurityRoute
  '/admin/tenant/residency': typeof AuthenticatedAdminTenantResidencyRoute
  '/admin/tenant/security': typeof AuthenticatedAdminTenantSecurityRoute
  '/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/dsr-request': typeof DsrRequestRoute
  '/dsr-status': typeof DsrStatusRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/acknowledgements': typeof AuthenticatedAcknowledgementsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/shared/$token': typeof SharedTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/acknowledgements': typeof AuthenticatedAdminAcknowledgementsRouteWithChildren
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/admin/disposition': typeof AuthenticatedAdminDispositionRoute
  '/admin/geofences': typeof AuthenticatedAdminGeofencesRoute
  '/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/admin/legal-holds': typeof AuthenticatedAdminLegalHoldsRoute
  '/admin/metadata-schema': typeof AuthenticatedAdminMetadataSchemaRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/admin/quarantine': typeof AuthenticatedAdminQuarantineRoute
  '/admin/residency': typeof AuthenticatedAdminResidencyRoute
  '/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/share-links': typeof AuthenticatedAdminShareLinksRoute
  '/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/legal-holds/my': typeof AuthenticatedLegalHoldsMyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/sessions': typeof AuthenticatedSettingsSessionsRoute
  '/settings/signatures': typeof AuthenticatedSettingsSignaturesRoute
  '/workflows/$instanceId': typeof AuthenticatedWorkflowsInstanceIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/admin/acknowledgements/$campaignId': typeof AuthenticatedAdminAcknowledgementsCampaignIdRoute
  '/admin/platform/internal-auth': typeof AuthenticatedAdminPlatformInternalAuthRoute
  '/admin/platform/schedules': typeof AuthenticatedAdminPlatformSchedulesRoute
  '/admin/platform/security': typeof AuthenticatedAdminPlatformSecurityRoute
  '/admin/tenant/residency': typeof AuthenticatedAdminTenantResidencyRoute
  '/admin/tenant/security': typeof AuthenticatedAdminTenantSecurityRoute
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/dsr-request': typeof DsrRequestRoute
  '/dsr-status': typeof DsrStatusRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/acknowledgements': typeof AuthenticatedAcknowledgementsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/acknowledgements': typeof AuthenticatedAdminAcknowledgementsRouteWithChildren
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/compliance': typeof AuthenticatedAdminComplianceRoute
  '/_authenticated/admin/connectors': typeof AuthenticatedAdminConnectorsRoute
  '/_authenticated/admin/disposition': typeof AuthenticatedAdminDispositionRoute
  '/_authenticated/admin/geofences': typeof AuthenticatedAdminGeofencesRoute
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsRoute
  '/_authenticated/admin/legal-holds': typeof AuthenticatedAdminLegalHoldsRoute
  '/_authenticated/admin/metadata-schema': typeof AuthenticatedAdminMetadataSchemaRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/privacy': typeof AuthenticatedAdminPrivacyRoute
  '/_authenticated/admin/quarantine': typeof AuthenticatedAdminQuarantineRoute
  '/_authenticated/admin/residency': typeof AuthenticatedAdminResidencyRoute
  '/_authenticated/admin/retention': typeof AuthenticatedAdminRetentionRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/share-links': typeof AuthenticatedAdminShareLinksRoute
  '/_authenticated/admin/sso': typeof AuthenticatedAdminSsoRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/_authenticated/legal-holds/my': typeof AuthenticatedLegalHoldsMyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/sessions': typeof AuthenticatedSettingsSessionsRoute
  '/_authenticated/settings/signatures': typeof AuthenticatedSettingsSignaturesRoute
  '/_authenticated/workflows/$instanceId': typeof AuthenticatedWorkflowsInstanceIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/admin/acknowledgements/$campaignId': typeof AuthenticatedAdminAcknowledgementsCampaignIdRoute
  '/_authenticated/admin/platform/internal-auth': typeof AuthenticatedAdminPlatformInternalAuthRoute
  '/_authenticated/admin/platform/schedules': typeof AuthenticatedAdminPlatformSchedulesRoute
  '/_authenticated/admin/platform/security': typeof AuthenticatedAdminPlatformSecurityRoute
  '/_authenticated/admin/tenant/residency': typeof AuthenticatedAdminTenantResidencyRoute
  '/_authenticated/admin/tenant/security': typeof AuthenticatedAdminTenantSecurityRoute
  '/_authenticated/workspaces/$workspaceId/': typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  '/_authenticated/workspaces/$workspaceId/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dsr-request'
    | '/dsr-status'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/settings'
    | '/acknowledgements'
    | '/notifications'
    | '/search'
    | '/tasks'
    | '/trash'
    | '/shared/$token'
    | '/admin/acknowledgements'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/compliance'
    | '/admin/connectors'
    | '/admin/disposition'
    | '/admin/geofences'
    | '/admin/groups'
    | '/admin/legal-holds'
    | '/admin/metadata-schema'
    | '/admin/permissions'
    | '/admin/privacy'
    | '/admin/quarantine'
    | '/admin/residency'
    | '/admin/retention'
    | '/admin/settings'
    | '/admin/share-links'
    | '/admin/sso'
    | '/admin/tags'
    | '/admin/tenants'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/legal-holds/my'
    | '/settings/notifications'
    | '/settings/sessions'
    | '/settings/signatures'
    | '/workflows/$instanceId'
    | '/admin/'
    | '/workspaces/'
    | '/admin/acknowledgements/$campaignId'
    | '/admin/platform/internal-auth'
    | '/admin/platform/schedules'
    | '/admin/platform/security'
    | '/admin/tenant/residency'
    | '/admin/tenant/security'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/dsr-request'
    | '/dsr-status'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/settings'
    | '/acknowledgements'
    | '/notifications'
    | '/search'
    | '/tasks'
    | '/trash'
    | '/shared/$token'
    | '/'
    | '/admin/acknowledgements'
    | '/admin/api-keys'
    | '/admin/audit-log'
    | '/admin/billing'
    | '/admin/compliance'
    | '/admin/connectors'
    | '/admin/disposition'
    | '/admin/geofences'
    | '/admin/groups'
    | '/admin/legal-holds'
    | '/admin/metadata-schema'
    | '/admin/permissions'
    | '/admin/privacy'
    | '/admin/quarantine'
    | '/admin/residency'
    | '/admin/retention'
    | '/admin/settings'
    | '/admin/share-links'
    | '/admin/sso'
    | '/admin/tags'
    | '/admin/tenants'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/legal-holds/my'
    | '/settings/notifications'
    | '/settings/sessions'
    | '/settings/signatures'
    | '/workflows/$instanceId'
    | '/admin'
    | '/workspaces'
    | '/admin/acknowledgements/$campaignId'
    | '/admin/platform/internal-auth'
    | '/admin/platform/schedules'
    | '/admin/platform/security'
    | '/admin/tenant/residency'
    | '/admin/tenant/security'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/documents/$documentId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/dsr-request'
    | '/dsr-status'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authenticated/settings'
    | '/_authenticated/acknowledgements'
    | '/_authenticated/notifications'
    | '/_authenticated/search'
    | '/_authenticated/tasks'
    | '/_authenticated/trash'
    | '/shared/$token'
    | '/_authenticated/'
    | '/_authenticated/admin/acknowledgements'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/compliance'
    | '/_authenticated/admin/connectors'
    | '/_authenticated/admin/disposition'
    | '/_authenticated/admin/geofences'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/legal-holds'
    | '/_authenticated/admin/metadata-schema'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/privacy'
    | '/_authenticated/admin/quarantine'
    | '/_authenticated/admin/residency'
    | '/_authenticated/admin/retention'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/share-links'
    | '/_authenticated/admin/sso'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/admin/workflows'
    | '/_authenticated/legal-holds/my'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/sessions'
    | '/_authenticated/settings/signatures'
    | '/_authenticated/workflows/$instanceId'
    | '/_authenticated/admin/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/admin/acknowledgements/$campaignId'
    | '/_authenticated/admin/platform/internal-auth'
    | '/_authenticated/admin/platform/schedules'
    | '/_authenticated/admin/platform/security'
    | '/_authenticated/admin/tenant/residency'
    | '/_authenticated/admin/tenant/security'
    | '/_authenticated/workspaces/$workspaceId/'
    | '/_authenticated/workspaces/$workspaceId/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  DsrRequestRoute: typeof DsrRequestRoute
  DsrStatusRoute: typeof DsrStatusRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsr-status': {
      id: '/dsr-status'
      path: '/dsr-status'
      fullPath: '/dsr-status'
      preLoaderRoute: typeof DsrStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsr-request': {
      id: '/dsr-request'
      path: '/dsr-request'
      fullPath: '/dsr-request'
      preLoaderRoute: typeof DsrRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acknowledgements': {
      id: '/_authenticated/acknowledgements'
      path: '/acknowledgements'
      fullPath: '/acknowledgements'
      preLoaderRoute: typeof AuthenticatedAcknowledgementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$instanceId': {
      id: '/_authenticated/workflows/$instanceId'
      path: '/workflows/$instanceId'
      fullPath: '/workflows/$instanceId'
      preLoaderRoute: typeof AuthenticatedWorkflowsInstanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/signatures': {
      id: '/_authenticated/settings/signatures'
      path: '/signatures'
      fullPath: '/settings/signatures'
      preLoaderRoute: typeof AuthenticatedSettingsSignaturesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/sessions': {
      id: '/_authenticated/settings/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof AuthenticatedSettingsSessionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/legal-holds/my': {
      id: '/_authenticated/legal-holds/my'
      path: '/legal-holds/my'
      fullPath: '/legal-holds/my'
      preLoaderRoute: typeof AuthenticatedLegalHoldsMyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workflows': {
      id: '/_authenticated/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/admin/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/sso': {
      id: '/_authenticated/admin/sso'
      path: '/admin/sso'
      fullPath: '/admin/sso'
      preLoaderRoute: typeof AuthenticatedAdminSsoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/share-links': {
      id: '/_authenticated/admin/share-links'
      path: '/admin/share-links'
      fullPath: '/admin/share-links'
      preLoaderRoute: typeof AuthenticatedAdminShareLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/retention': {
      id: '/_authenticated/admin/retention'
      path: '/admin/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AuthenticatedAdminRetentionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/residency': {
      id: '/_authenticated/admin/residency'
      path: '/admin/residency'
      fullPath: '/admin/residency'
      preLoaderRoute: typeof AuthenticatedAdminResidencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/quarantine': {
      id: '/_authenticated/admin/quarantine'
      path: '/admin/quarantine'
      fullPath: '/admin/quarantine'
      preLoaderRoute: typeof AuthenticatedAdminQuarantineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/privacy': {
      id: '/_authenticated/admin/privacy'
      path: '/admin/privacy'
      fullPath: '/admin/privacy'
      preLoaderRoute: typeof AuthenticatedAdminPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/metadata-schema': {
      id: '/_authenticated/admin/metadata-schema'
      path: '/admin/metadata-schema'
      fullPath: '/admin/metadata-schema'
      preLoaderRoute: typeof AuthenticatedAdminMetadataSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/legal-holds': {
      id: '/_authenticated/admin/legal-holds'
      path: '/admin/legal-holds'
      fullPath: '/admin/legal-holds'
      preLoaderRoute: typeof AuthenticatedAdminLegalHoldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/geofences': {
      id: '/_authenticated/admin/geofences'
      path: '/admin/geofences'
      fullPath: '/admin/geofences'
      preLoaderRoute: typeof AuthenticatedAdminGeofencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/disposition': {
      id: '/_authenticated/admin/disposition'
      path: '/admin/disposition'
      fullPath: '/admin/disposition'
      preLoaderRoute: typeof AuthenticatedAdminDispositionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/connectors': {
      id: '/_authenticated/admin/connectors'
      path: '/admin/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AuthenticatedAdminConnectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/compliance': {
      id: '/_authenticated/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AuthenticatedAdminComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/admin/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/acknowledgements': {
      id: '/_authenticated/admin/acknowledgements'
      path: '/admin/acknowledgements'
      fullPath: '/admin/acknowledgements'
      preLoaderRoute: typeof AuthenticatedAdminAcknowledgementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$workspaceId/': {
      id: '/_authenticated/workspaces/$workspaceId/'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenant/security': {
      id: '/_authenticated/admin/tenant/security'
      path: '/admin/tenant/security'
      fullPath: '/admin/tenant/security'
      preLoaderRoute: typeof AuthenticatedAdminTenantSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/tenant/residency': {
      id: '/_authenticated/admin/tenant/residency'
      path: '/admin/tenant/residency'
      fullPath: '/admin/tenant/residency'
      preLoaderRoute: typeof AuthenticatedAdminTenantResidencyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/platform/security': {
      id: '/_authenticated/admin/platform/security'
      path: '/admin/platform/security'
      fullPath: '/admin/platform/security'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/platform/schedules': {
      id: '/_authenticated/admin/platform/schedules'
      path: '/admin/platform/schedules'
      fullPath: '/admin/platform/schedules'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/platform/internal-auth': {
      id: '/_authenticated/admin/platform/internal-auth'
      path: '/admin/platform/internal-auth'
      fullPath: '/admin/platform/internal-auth'
      preLoaderRoute: typeof AuthenticatedAdminPlatformInternalAuthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/acknowledgements/$campaignId': {
      id: '/_authenticated/admin/acknowledgements/$campaignId'
      path: '/$campaignId'
      fullPath: '/admin/acknowledgements/$campaignId'
      preLoaderRoute: typeof AuthenticatedAdminAcknowledgementsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAdminAcknowledgementsRoute
    }
    '/_authenticated/workspaces/$workspaceId/documents/$documentId': {
      id: '/_authenticated/workspaces/$workspaceId/documents/$documentId'
      path: '/workspaces/$workspaceId/documents/$documentId'
      fullPath: '/workspaces/$workspaceId/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSessionsRoute: typeof AuthenticatedSettingsSessionsRoute
  AuthenticatedSettingsSignaturesRoute: typeof AuthenticatedSettingsSignaturesRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsSessionsRoute: AuthenticatedSettingsSessionsRoute,
    AuthenticatedSettingsSignaturesRoute: AuthenticatedSettingsSignaturesRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedAdminAcknowledgementsRouteChildren {
  AuthenticatedAdminAcknowledgementsCampaignIdRoute: typeof AuthenticatedAdminAcknowledgementsCampaignIdRoute
}

const AuthenticatedAdminAcknowledgementsRouteChildren: AuthenticatedAdminAcknowledgementsRouteChildren =
  {
    AuthenticatedAdminAcknowledgementsCampaignIdRoute:
      AuthenticatedAdminAcknowledgementsCampaignIdRoute,
  }

const AuthenticatedAdminAcknowledgementsRouteWithChildren =
  AuthenticatedAdminAcknowledgementsRoute._addFileChildren(
    AuthenticatedAdminAcknowledgementsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAcknowledgementsRoute: typeof AuthenticatedAcknowledgementsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminAcknowledgementsRoute: typeof AuthenticatedAdminAcknowledgementsRouteWithChildren
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminComplianceRoute: typeof AuthenticatedAdminComplianceRoute
  AuthenticatedAdminConnectorsRoute: typeof AuthenticatedAdminConnectorsRoute
  AuthenticatedAdminDispositionRoute: typeof AuthenticatedAdminDispositionRoute
  AuthenticatedAdminGeofencesRoute: typeof AuthenticatedAdminGeofencesRoute
  AuthenticatedAdminGroupsRoute: typeof AuthenticatedAdminGroupsRoute
  AuthenticatedAdminLegalHoldsRoute: typeof AuthenticatedAdminLegalHoldsRoute
  AuthenticatedAdminMetadataSchemaRoute: typeof AuthenticatedAdminMetadataSchemaRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPrivacyRoute: typeof AuthenticatedAdminPrivacyRoute
  AuthenticatedAdminQuarantineRoute: typeof AuthenticatedAdminQuarantineRoute
  AuthenticatedAdminResidencyRoute: typeof AuthenticatedAdminResidencyRoute
  AuthenticatedAdminRetentionRoute: typeof AuthenticatedAdminRetentionRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShareLinksRoute: typeof AuthenticatedAdminShareLinksRoute
  AuthenticatedAdminSsoRoute: typeof AuthenticatedAdminSsoRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminWorkflowsRoute: typeof AuthenticatedAdminWorkflowsRoute
  AuthenticatedLegalHoldsMyRoute: typeof AuthenticatedLegalHoldsMyRoute
  AuthenticatedWorkflowsInstanceIdRoute: typeof AuthenticatedWorkflowsInstanceIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedAdminPlatformInternalAuthRoute: typeof AuthenticatedAdminPlatformInternalAuthRoute
  AuthenticatedAdminPlatformSchedulesRoute: typeof AuthenticatedAdminPlatformSchedulesRoute
  AuthenticatedAdminPlatformSecurityRoute: typeof AuthenticatedAdminPlatformSecurityRoute
  AuthenticatedAdminTenantResidencyRoute: typeof AuthenticatedAdminTenantResidencyRoute
  AuthenticatedAdminTenantSecurityRoute: typeof AuthenticatedAdminTenantSecurityRoute
  AuthenticatedWorkspacesWorkspaceIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceIdIndexRoute
  AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAcknowledgementsRoute: AuthenticatedAcknowledgementsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminAcknowledgementsRoute:
    AuthenticatedAdminAcknowledgementsRouteWithChildren,
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminComplianceRoute: AuthenticatedAdminComplianceRoute,
  AuthenticatedAdminConnectorsRoute: AuthenticatedAdminConnectorsRoute,
  AuthenticatedAdminDispositionRoute: AuthenticatedAdminDispositionRoute,
  AuthenticatedAdminGeofencesRoute: AuthenticatedAdminGeofencesRoute,
  AuthenticatedAdminGroupsRoute: AuthenticatedAdminGroupsRoute,
  AuthenticatedAdminLegalHoldsRoute: AuthenticatedAdminLegalHoldsRoute,
  AuthenticatedAdminMetadataSchemaRoute: AuthenticatedAdminMetadataSchemaRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPrivacyRoute: AuthenticatedAdminPrivacyRoute,
  AuthenticatedAdminQuarantineRoute: AuthenticatedAdminQuarantineRoute,
  AuthenticatedAdminResidencyRoute: AuthenticatedAdminResidencyRoute,
  AuthenticatedAdminRetentionRoute: AuthenticatedAdminRetentionRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminShareLinksRoute: AuthenticatedAdminShareLinksRoute,
  AuthenticatedAdminSsoRoute: AuthenticatedAdminSsoRoute,
  AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminWorkflowsRoute: AuthenticatedAdminWorkflowsRoute,
  AuthenticatedLegalHoldsMyRoute: AuthenticatedLegalHoldsMyRoute,
  AuthenticatedWorkflowsInstanceIdRoute: AuthenticatedWorkflowsInstanceIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedAdminPlatformInternalAuthRoute:
    AuthenticatedAdminPlatformInternalAuthRoute,
  AuthenticatedAdminPlatformSchedulesRoute:
    AuthenticatedAdminPlatformSchedulesRoute,
  AuthenticatedAdminPlatformSecurityRoute:
    AuthenticatedAdminPlatformSecurityRoute,
  AuthenticatedAdminTenantResidencyRoute:
    AuthenticatedAdminTenantResidencyRoute,
  AuthenticatedAdminTenantSecurityRoute: AuthenticatedAdminTenantSecurityRoute,
  AuthenticatedWorkspacesWorkspaceIdIndexRoute:
    AuthenticatedWorkspacesWorkspaceIdIndexRoute,
  AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute:
    AuthenticatedWorkspacesWorkspaceIdDocumentsDocumentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  DsrRequestRoute: DsrRequestRoute,
  DsrStatusRoute: DsrStatusRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
