// ESLint flat config (ESLint 10).
//
// Replaces the legacy .eslintrc model — flat config is the only
// supported format on ESLint 9+. Per-file overrides go into
// additional config objects below; see the typescript-eslint docs
// for type-aware rules once we're ready to opt into them.
//
// Package.json `type` is "module", so this file uses ESM imports.

import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      // Auto-generated by the TanStack Router plugin; lint complains
      // about its formatting choices and there's no point fighting it.
      'src/routeTree.gen.ts',
      // Generated indexes — regenerated on every build.
      'src/generated/**',
      // Vendored / generated GraphQL operations.
      'src/lib/graphql-operations.ts',
      // Playwright/e2e snapshots + reports.
      'web/test-results/**',
      'web/e2e/**',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      // `configs.flat['recommended-latest']` is the flat-config-shaped
      // export from eslint-plugin-react-hooks 7+. The non-`flat` one
      // is legacy .eslintrc style and ESLint 10 rejects it.
      reactHooks.configs.flat['recommended-latest'],
    ],
    plugins: {
      // eslint-plugin-react-refresh has no flat-config helper export
      // in 0.5.x — register it manually so the rule below resolves.
      'react-refresh': reactRefresh,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
    },
    rules: {
      // Project-wide rule from the bug-fix pass: discourage `any`
      // (warn rather than error so the migration to fully-typed
      // code can land incrementally — flip to 'error' once the
      // warnings list is small).
      '@typescript-eslint/no-explicit-any': 'warn',
      // react-hooks 7 added several rules that didn't exist in
      // earlier versions; the codebase pre-dates them. Demote to
      // `warn` so lint passes today and we can promote rules to
      // `error` as the codebase gets cleaned up. The warnings
      // remain visible in the lint output so cleanup work has a
      // concrete list to chew through.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/static-components': 'warn',
      'react-hooks/immutability': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/incompatible-library': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/globals': 'warn',
      'react-hooks/use-memo': 'warn',
      'react-hooks/void-use-memo': 'warn',
      // The codebase has many intentional `_unusedVar` patterns;
      // honour the underscore convention.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // React fast-refresh — only allow component exports + hook
      // exports from .tsx files (default Vite recommendation).
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
    },
  },
  // Node-side scripts under web/scripts/ run with the node-globals
  // set (process, __dirname, etc.). Apply node globals to .mjs/.js
  // there so eslint doesn't flag `process` as undefined.
  {
    files: ['scripts/**/*.{js,mjs,cjs}', '*.config.{js,mjs,ts}'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  // Vitest + test files use vitest globals (describe, it, expect, vi)
  // when globals=true in vitest.config — pull them in so lint
  // doesn't fail on every test file.
  {
    files: ['**/*.{test,spec}.{ts,tsx}', 'src/test/**/*.{ts,tsx}'],
    languageOptions: {
      globals: {
        ...globals.node,
        // Vitest matches its globals to Jest's, which `globals` exports.
        ...globals.jest,
      },
    },
    rules: {
      // Test files often need `any` for mock typing — relax.
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
)
